- checkBalancedBinaryTree.js
> will solve is balanced

- mergeTwoSortedLists.js
> complete mergeTwoSortedLLs

- binarySearch.ts
> complete binarySearch

- floodFill.ts
> complete floodFill with ease

- LLCycle.ts
- checkBalancedBinaryTree.js
> complete LLCycle and fix isBalanced

- firstBadVersion.ts
> complete firstBadVersion in phenomenal time complexity

- ransomNotes.ts
> complete ransomNote

- containerwitwater.ts
> complete containerwitH2O

- climbingStairs.ts
- longestPalindrome.ts
> Longest palindrome

- reverseLL.ts
> complete reverseLL

- majorityElement.ts
- reverseLL.ts
> Majority element

- middleLL.ts
> complete middle of LL

- maxDepthBST.ts
- middleLL.ts
> Max depth bst

- containsDuplicate.ts
- maxDepthBST.ts
- middleLL.ts
> Contains duplicate

- maxSubarray.ts
> complete maxSubArray

- insertInterval.ts
> Insert interval

- 01matrix.ts
> non working solution of 01matrix

- kClosestPointsToOrigin.ts
> complete kOrigin

- kClosestPointsToOrigin.ts
- substringWithoutRepeats.ts
> complete longestSubstringWithoutRepeats

- 3Sum.ts
> complete 3Sum with phenomenal memory
